'use strict';

const redact = require('./redact');

const TYPE_WEIGHT = { wontfix: 4, constraint: 3, decision: 2, state: 1 };
const DURABILITY_WEIGHT = { permanent: 3, 'until-changed': 2, session: 1 };

const HEADINGS = {
  wontfix: 'Already tried and rejected. Do not propose these again.',
  constraint: 'Rules that must hold.',
  decision: 'Decisions already made.',
  state: 'Current state.'
};

const TYPE_ORDER = ['wontfix', 'constraint', 'decision', 'state'];

// Deliberately crude. A real tokenizer is not worth a dependency here.
function estimateTokens(text) {
  return Math.ceil(text.length / 4);
}

function matchesScope(entry, scope) {
  if (!scope) return false;
  if (!entry.scope) return false;
  return entry.scope.startsWith(scope) || scope.startsWith(entry.scope);
}

function rank(entries, scope) {
  return entries.slice().sort((a, b) => {
    const scopeDiff = Number(matchesScope(b, scope)) - Number(matchesScope(a, scope));
    if (scopeDiff !== 0) return scopeDiff;
    const typeDiff = (TYPE_WEIGHT[b.type] || 0) - (TYPE_WEIGHT[a.type] || 0);
    if (typeDiff !== 0) return typeDiff;
    const durDiff =
      (DURABILITY_WEIGHT[b.durability] || 0) - (DURABILITY_WEIGHT[a.durability] || 0);
    if (durDiff !== 0) return durDiff;
    return Date.parse(b.created || 0) - Date.parse(a.created || 0);
  });
}

// Entries written by an older version, or hand-edited into the file, have not
// been through the write-path sanitizer. Do it again here.
function safe(text) {
  return redact.sanitizeText(String(text || '')).text;
}

function renderEntry(entry) {
  let line = `- ${safe(entry.title)}`;
  if (entry.why) line += `. Reason: ${safe(entry.why)}`;
  if (entry.scope) line += ` [${safe(entry.scope)}]`;
  return line;
}

function select(entries, budget, scope, reserve) {
  const ranked = rank(entries, scope);
  const kept = [];
  const dropped = [];
  let used = 60 + (reserve || 0);
  for (const entry of ranked) {
    const cost = estimateTokens(renderEntry(entry)) + 2;
    if (used + cost > budget) {
      dropped.push(entry);
      continue;
    }
    used += cost;
    kept.push(entry);
  }
  return { kept, dropped, used };
}

function countByType(entries) {
  const counts = {};
  for (const entry of entries) {
    counts[entry.type] = (counts[entry.type] || 0) + 1;
  }
  return TYPE_ORDER.filter((t) => counts[t]).map((t) => `${counts[t]} ${t}`);
}

function render(entries, options = {}) {
  const budget = options.budget || 1200;
  const instruction = options.instruction ? String(options.instruction) : '';
  const { kept, dropped } = select(
    entries,
    budget,
    options.scope,
    instruction ? estimateTokens(instruction) : 0
  );

  const lines = [];
  lines.push('## Project context (generated by wontfix)');
  lines.push('');
  if (instruction) {
    lines.push(instruction);
    lines.push('');
  }

  if (kept.length === 0) {
    lines.push('No entries recorded yet.');
  }

  for (const type of TYPE_ORDER) {
    const group = kept.filter((e) => e.type === type);
    if (group.length === 0) continue;
    lines.push(`### ${HEADINGS[type]}`);
    for (const entry of group) lines.push(renderEntry(entry));
    lines.push('');
  }

  const total = kept.length + dropped.length;
  const omitted =
    dropped.length === 0 ? '' : ` ${dropped.length} omitted (${countByType(dropped).join(', ')}).`;

  if (options.stampDate) {
    lines.push(
      `<!-- wontfix export: ${kept.length} of ${total} entries, budget ${budget}, ` +
        `${options.stampDate}.${omitted} Re-run "wontfix export" if this looks stale. -->`
    );
  } else {
    lines.push(
      `<!-- wontfix: ${kept.length} of ${total} entries packed.${omitted} Budget ${budget}. -->`
    );
  }
  return { text: lines.join('\n'), kept, dropped };
}

module.exports = {
  safe,
  rank,
  render,
};
